FROM node:20-alpine as builder

WORKDIR /app

RUN corepack enable

RUN corepack prepare yarn@4.5.0 --activate

# Copy package files
COPY webui/package.json webui/yarn.lock ./


# Install dependencies
RUN yarn install

# Copy source files
COPY webui/ .


EXPOSE 5173


# Run in development mode
CMD ["yarn", "dev", "--host"]



